apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w9e96wzd7-java-springboot
  janus-idp.io/tekton: w9e96wzd7-java-springboot
  backstage.io/kubernetes-id: w9e96wzd7-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w9e96wzd7-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
